# Generated by Django 5.1.1 on 2025-09-21 14:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gonulluluk_no",
                    models.CharField(
                        blank=True,
                        help_text="Otomatik üretilen gönüllülük numarası (G0123456789)",
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("ad", models.CharField(max_length=50, verbose_name="Ad")),
                ("soyad", models.CharField(max_length=50, verbose_name="Soyad")),
                (
                    "telefon",
                    models.CharField(
                        help_text="Başında 0 olmayan 10 haneli telefon numarası",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Telefon numarası 10 haneli olmalı ve 0 ile başlamamalı (5XXXXXXXXX)",
                                regex="^[1-9][0-9]{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "sehir",
                    models.CharField(
                        choices=[
                            ("adana", "Adana"),
                            ("adiyaman", "Adıyaman"),
                            ("afyonkarahisar", "Afyonkarahisar"),
                            ("agri", "Ağrı"),
                            ("amasya", "Amasya"),
                            ("ankara", "Ankara"),
                            ("antalya", "Antalya"),
                            ("artvin", "Artvin"),
                            ("aydin", "Aydın"),
                            ("balikesir", "Balıkesir"),
                            ("bilecik", "Bilecik"),
                            ("bingol", "Bingöl"),
                            ("bitlis", "Bitlis"),
                            ("bolu", "Bolu"),
                            ("burdur", "Burdur"),
                            ("bursa", "Bursa"),
                            ("canakkale", "Çanakkale"),
                            ("cankiri", "Çankırı"),
                            ("corum", "Çorum"),
                            ("denizli", "Denizli"),
                            ("diyarbakir", "Diyarbakır"),
                            ("edirne", "Edirne"),
                            ("elazig", "Elazığ"),
                            ("erzincan", "Erzincan"),
                            ("erzurum", "Erzurum"),
                            ("eskisehir", "Eskişehir"),
                            ("gaziantep", "Gaziantep"),
                            ("giresun", "Giresun"),
                            ("gumushane", "Gümüşhane"),
                            ("hakkari", "Hakkâri"),
                            ("hatay", "Hatay"),
                            ("isparta", "Isparta"),
                            ("mersin", "Mersin"),
                            ("istanbul", "İstanbul"),
                            ("izmir", "İzmir"),
                            ("kars", "Kars"),
                            ("kastamonu", "Kastamonu"),
                            ("kayseri", "Kayseri"),
                            ("kirklareli", "Kırklareli"),
                            ("kirsehir", "Kırşehir"),
                            ("kocaeli", "Kocaeli"),
                            ("konya", "Konya"),
                            ("kutahya", "Kütahya"),
                            ("malatya", "Malatya"),
                            ("manisa", "Manisa"),
                            ("kahramanmaras", "Kahramanmaraş"),
                            ("mardin", "Mardin"),
                            ("mugla", "Muğla"),
                            ("mus", "Muş"),
                            ("nevsehir", "Nevşehir"),
                            ("nigde", "Niğde"),
                            ("ordu", "Ordu"),
                            ("rize", "Rize"),
                            ("sakarya", "Sakarya"),
                            ("samsun", "Samsun"),
                            ("siirt", "Siirt"),
                            ("sinop", "Sinop"),
                            ("sivas", "Sivas"),
                            ("tekirdag", "Tekirdağ"),
                            ("tokat", "Tokat"),
                            ("trabzon", "Trabzon"),
                            ("tunceli", "Tunceli"),
                            ("sanliurfa", "Şanlıurfa"),
                            ("usak", "Uşak"),
                            ("van", "Van"),
                            ("yozgat", "Yozgat"),
                            ("zonguldak", "Zonguldak"),
                            ("aksaray", "Aksaray"),
                            ("bayburt", "Bayburt"),
                            ("karaman", "Karaman"),
                            ("kirikkale", "Kırıkkale"),
                            ("batman", "Batman"),
                            ("sirnak", "Şırnak"),
                            ("bartin", "Bartın"),
                            ("ardahan", "Ardahan"),
                            ("igdir", "Iğdır"),
                            ("yalova", "Yalova"),
                            ("karabuk", "Karabük"),
                            ("kilis", "Kilis"),
                            ("osmaniye", "Osmaniye"),
                            ("duzce", "Düzce"),
                        ],
                        max_length=50,
                        verbose_name="Şehir",
                    ),
                ),
                (
                    "gonullu_tipi",
                    models.CharField(
                        choices=[
                            ("collection", "Collection Volunteer"),
                            ("transport", "Transport Volunteer"),
                            ("distribution", "Distribution Volunteer"),
                            ("mixed", "Mixed Volunteer (All Tasks)"),
                        ],
                        max_length=20,
                        verbose_name="Gönüllü Tipi",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Gönüllünün aktif olup olmadığını belirtir",
                        verbose_name="Aktif Durum",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Kayıt Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Son Güncelleme"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Django User modeli ile bağlantı",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gönüllü",
                "verbose_name_plural": "Gönüllüler",
                "db_table": "volunteers",
                "ordering": ["-created_at"],
            },
        ),
    ]
