# Generated by Django 5.1.1 on 2025-09-21 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0001_initial"),
    ]

    operations = []
