# Generated by Django 5.1.1 on 2025-09-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0002_auto_20250921_1732"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="gonullu_tipi",
            field=models.CharField(
                choices=[
                    ("toplama", "Toplama Gönüllüsü"),
                    ("tasima", "Taşıma Gönüllüsü"),
                    ("dagitim", "Dağıtım Gönüllüsü"),
                    ("karma", "Karma Gönüllü (Tüm Görevler)"),
                ],
                max_length=20,
                verbose_name="Gönüllü Tipi",
            ),
        ),
    ]
