# Generated by Django 5.1.1 on 2025-09-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0003_alter_volunteer_gonullu_tipi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="gonulluluk_no",
            field=models.CharField(
                blank=True,
                help_text="Otomatik üretilen gönüllülük numarası (G000000000)",
                max_length=12,
                unique=True,
            ),
        ),
    ]
