version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ayika-postgres
    environment:
      POSTGRES_DB: ayika_db
      POSTGRES_USER: ayika_user
      POSTGRES_PASSWORD: ayika_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ayika-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ayika_user -d ayika_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for Caching and Celery
  redis:
    image: redis:7-alpine
    container_name: ayika-redis
    ports:
      - "6379:6379"
    networks:
      - ayika-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Django Backend - Development
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: ayika-backend-dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://ayika_user:ayika_password@postgres:5432/ayika_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ayika-network
    restart: unless-stopped
    profiles:
      - dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health/"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3

  # Django Backend - Production
  backend-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: ayika-backend-prod
    ports:
      - "8000:8000"
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://ayika_user:ayika_password@postgres:5432/ayika_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ayika-network
    restart: unless-stopped
    profiles:
      - prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health/"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3

volumes:
  postgres_data:
  media_volume:
  static_volume:

networks:
  ayika-network:
    driver: bridge
