# Generated by Django 5.1.1 on 2025-09-22 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad",
                    models.CharField(
                        help_text="Gönderen kişinin adı",
                        max_length=50,
                        verbose_name="Ad",
                    ),
                ),
                (
                    "soyad",
                    models.CharField(
                        help_text="Gönderen kişinin soyadı",
                        max_length=50,
                        verbose_name="Soyad",
                    ),
                ),
                (
                    "telefon",
                    models.CharField(
                        help_text="5XXXXXXXXX formatında",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Telefon numarası 5XXXXXXXXX formatında olmalıdır.",
                                regex="^5\\d{9}$",
                            )
                        ],
                        verbose_name="Telefon Numarası",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Geçerli bir e-posta adresi",
                        max_length=254,
                        verbose_name="E-posta Adresi",
                    ),
                ),
                (
                    "sehir",
                    models.CharField(
                        help_text="Gönderen kişinin şehri",
                        max_length=50,
                        verbose_name="Şehir",
                    ),
                ),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("genel", "Genel Bilgi"),
                            ("gonulluluk", "Gönüllülük"),
                            ("yardim", "Yardım Talebi"),
                            ("bagis", "Bağış"),
                            ("teknik", "Teknik Destek"),
                            ("medya", "Medya ve Basın"),
                            ("isbirligi", "İş Birliği"),
                            ("sikayet", "Şikayet ve Öneri"),
                        ],
                        help_text="Mesajın kategorisi",
                        max_length=20,
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "konu",
                    models.CharField(
                        help_text="Mesajın konusu", max_length=200, verbose_name="Konu"
                    ),
                ),
                (
                    "mesaj",
                    models.TextField(
                        help_text="Detaylı mesaj içeriği", verbose_name="Mesaj"
                    ),
                ),
                (
                    "dosya",
                    models.FileField(
                        blank=True,
                        help_text="İsteğe bağlı dosya eki (Max 10MB)",
                        null=True,
                        upload_to="contact_files/%Y/%m/",
                        verbose_name="Ek Dosya",
                    ),
                ),
                (
                    "kvkk_onayi",
                    models.BooleanField(
                        default=False,
                        help_text="Kişisel verilerin korunması politikası onayı",
                        verbose_name="KVKK Onayı",
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("yeni", "Yeni"),
                            ("okundu", "Okundu"),
                            ("cevaplanıyor", "Cevaplanıyor"),
                            ("cevaplandi", "Cevaplandı"),
                            ("kapandi", "Kapatıldı"),
                        ],
                        default="yeni",
                        help_text="Mesajın işlem durumu",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "oncelik",
                    models.CharField(
                        choices=[
                            ("dusuk", "Düşük"),
                            ("normal", "Normal"),
                            ("yuksek", "Yüksek"),
                            ("acil", "Acil"),
                        ],
                        default="normal",
                        help_text="Mesajın öncelik seviyesi",
                        max_length=20,
                        verbose_name="Öncelik",
                    ),
                ),
                (
                    "olusturulma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "son_degisiklik",
                    models.DateTimeField(auto_now=True, verbose_name="Son Değişiklik"),
                ),
                (
                    "admin_notu",
                    models.TextField(
                        blank=True,
                        help_text="Yönetici tarafından eklenen notlar",
                        null=True,
                        verbose_name="Admin Notu",
                    ),
                ),
                (
                    "cevaplayan_admin",
                    models.CharField(
                        blank=True,
                        help_text="Mesajı cevaplayan yönetici",
                        max_length=100,
                        null=True,
                        verbose_name="Cevaplayan Admin",
                    ),
                ),
                (
                    "cevap_tarihi",
                    models.DateTimeField(
                        blank=True,
                        help_text="Mesajın cevaplanma tarihi",
                        null=True,
                        verbose_name="Cevap Tarihi",
                    ),
                ),
                (
                    "ip_adresi",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Gönderen IP adresi",
                        null=True,
                        verbose_name="IP Adresi",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Tarayıcı bilgisi",
                        null=True,
                        verbose_name="User Agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "İletişim Mesajı",
                "verbose_name_plural": "İletişim Mesajları",
                "db_table": "contact_messages",
                "ordering": ["-olusturulma_tarihi"],
            },
        ),
    ]
