version: '3.8'

services:
  # Development environment
  ayika-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: ayika-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    networks:
      - ayika-network
    restart: unless-stopped
    profiles:
      - dev
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173/"]
      interval: 30s
      timeout: 3s
      start_period: 10s
      retries: 3

  # Production environment
  ayika-frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: ayika-frontend-prod
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - ayika-network
    restart: unless-stopped
    profiles:
      - prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3

networks:
  ayika-network:
    driver: bridge
