# Generated by Django 5.1.1 on 2025-09-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cargo", "0002_make_toplama_gonullusu_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kargo",
            name="kargo_no",
            field=models.CharField(
                help_text="AYK000000000 formatında otomatik oluşturulur",
                max_length=12,
                unique=True,
                verbose_name="Kargo Numarası",
            ),
        ),
    ]
